### ISSUE TITLE
Notes and Feedback from Attempted Runs

### ISSUE THREAD

**Issue by francisrocket** [Technion-Kishony-lab/data-to-paper#22]
Tried out the program with some sample data, here's some notes and feedback that I've gathered from those runs:

1. The multi-turn self debugging process is inconsistent (in large part due to the nature of LLMs), but despite being programmed to iterate 20 times, it may sometimes start another set of 20 iterations before finishing it's original 20 (ex. it may go from 4/20 to 1/20)
2. The GPT is not exactly powerful enough to always end up with fully working code just by generating and reviewing its own generated code. It can get stuck, and also the results are not consistent as mentioned earlier. For example, multiple runs using the same input can end up with different hypotheses.
3. Can get stuck quite often based on the task it is assigned and the amount of additional support given through prompts, seems to be random whether or not the generation will go through successfully
4. Doesn't allow for direct human editing of the generated code/outputs, human input is only available as "feedback". Also, human feedback isn't available at all stages, could be available more to allow for human intervention when it gets stuck
5. The most important part, from what I've seen, is the "hypothesis plan". As mentioned, the output is random so it is hard to get the same hypothesis in different runs, but because the hypothesis is one of the most important parts of a paper in general, whether it will get stuck or not in later portions, especially "data analysis", is heavily determined by the hypothesis. 
6. Despite the preference/preprogramming for doing statistical analysis, it is still able to generate code for other things such as machine learning due to the LLM behind it. However, when asked in the hypothesis to create a classifier, code for it would be generated in the data analysis tab, but it would get stuck while looping through the debugging/regeneration. 
7. The generated papers are generally quite short, about 5 pages when excluding references and code
8. Tested it in performing hypothesis testing against data with a human "ground truth", and found that it was able to corroborate human findings, meaning that even from a non-stats expert's perspective, the findings have some validity
9. Would be helpful to allow for more human feedback after each debugging iteration or direct human editing of the code, generally more opportunities for the human to be involved would be helpful. Oftentimes it gets stuck trying to debug an issue in it's generated code and it feels as if the human is "locked out" of the process.
10. Currently, it usually allows for human intervention when it gets to a new step (mission prompt), or finishes a step and is asking for any final feedback. Sometimes, it might run into an error in its code, and it doesn't allow for human intervention until the code runs successfully and it's about to move onto the next step. These may be trivial errors such as syntax errors, which we humans can resolve with a single line, either as feedback or even directly onto the code product that is generated.
11. Generated code is not saved until the step is completed, making it more difficult of a process for the user to identify the issue and try to address it in the next iteration (adjusting prompting/feedback)
12. Liked the feature of saving the runs and allowing for old projects to be reran quickly and being able to see logs and information from past runs

**Comment by TalIfargan** [comment]
Thanks a lot for your detailed feedback! We tried to answer some of your comments below. We just pushed a major revision to the AI-Human review system which addresses several of your suggestions (Commit: e2832eb638178f0cc86c403a8c75ed9583260d49). Would be great to have your feedback also on this new version! :)

**1. The multi-turn self debugging process is inconsistent (in large part due to the nature of LLMs), but despite being programmed to iterate 20 times, it may sometimes start another set of 20 iterations before finishing it's original 20 (ex. it may go from 4/20 to 1/20)**

Please note that we have two types of setbacks when debugging code, the ones that you have correctly identified are the debug iterations, beside them there are what we call “revisions” or “attempts”. Each such revision can include any number of debug iterations (e.g. the default value for data analysis code is 20 debug iterations). If we pass the number of allowed debug iterations in a specific revision/attempt step we start a fresh one, deleting all the past code we have produced, to avoid that it gets stuck in the wrong direction. This mechanism can be envisioned as a nested loop structure:

```
for code_revision in max_code_revisions:
    code = write_code()
    for debug_iteration in max_debug_iterations_per_attempt:
        If not is_bug(code):
            break
        code = debug_code(code)
    review = get_review(code)
    post_review_comments(review)
```

To change those number look at the following variables in the code:
```
max_debug_iterations_per_attempt: int = 20
max_code_revisions: int = 3
```

**2. The GPT is not exactly powerful enough to always end up with fully working code just by generating and reviewing its own generated code. It can get stuck, and also the results are not consistent as mentioned earlier. For example, multiple runs using the same input can end up with different hypotheses.**

Currently, this is an inherent drawback of even the SOTA models. Keeping in mind that they are basically highly trained and optimized statistical models of language (and code), they are not always able to produce working code and debug their own mistakes.
We have put a lot of effort into recognizing common pitfalls and providing them with appropriate feedback that will allow them to overcome the mistakes that recur.

**3. Can get stuck quite often based on the task it is assigned and the amount of additional support given through prompts, seems to be random whether or not the generation will go through successfully**

From our tests, the system's ability to write correct code is dependent on the complexity of the data, the complexity of the research goal and the quality of data description. If you feel that in your case the system is not persistent, try to look into the dataset and file descriptions (take examples from the datasets we have added to the repo). From there you should look into the complexity of the research goal you try to achieve, as we both agreed above, too complex goals are still too hard for current SOTA models. If you still cannot get the system to converge into working code, maybe your dataset is too complex, includes too many variables, or requires too many steps to process.

**4. Doesn't allow for direct human editing of the generated code/outputs, human input is only available as "feedback". Also, human feedback isn't available at all stages, could be available more to allow for human intervention when it gets stuck**

We deliberately placed humans in a reviewer role rather than a performer role to focus on refining model outputs. We are now in a stage of reimagining human intervention and your (and others’) feedback about this can really help reshape the UX. Regarding the second point, we are in the process of updating this to allow human intervention also during the table creation steps.

**5. The most important part, from what I've seen, is the "hypothesis plan". As mentioned, the output is random so it is hard to get the same hypothesis in different runs, but because the hypothesis is one of the most important parts of a paper in general, whether it will get stuck or not in later portions, especially "data analysis", is heavily determined by the hypothesis.** 

As I mentioned for point 3, the dataset description can play a major role in improving the reliability of the process. In addition, if you are trying to achieve a specific research goal, use the system in fixed-goal mode by providing a research goal.

**6. Despite the preference/preprogramming for doing statistical analysis, it is still able to generate code for other things such as machine learning due to the LLM behind it. However, when asked in the hypothesis to create a classifier, code for it would be generated in the data analysis tab, but it would get stuck while looping through the debugging/regeneration.** 

Please note that at this point we chose to restrict the system to produce code that includes a statistical test. This can be one of many reasons for the inability of the coding steps to converge. Try to look carefully into the errors you get and iteratively improve your inputs (data, metadata, research goal, etc…) to overcome those errors.

**7. The generated papers are generally quite short, about 5 pages when excluding references and code**

We found the chosen sections and relevant mission prompts to work well for our test cases. To tailor the length and detail of the generated content, you can adjust the mission prompts accordingly, allowing for more comprehensive sections as required by your formatting and stylistic needs.

**8. Tested it in performing hypothesis testing against data with a human "ground truth", and found that it was able to corroborate human findings, meaning that even from a non-stats expert's perspective, the findings have some validity**

That's cool to know! We believe that with further advancement of LLMs we are going to see these types of abilities improving even further! 

**9. Would be helpful to allow for more human feedback after each debugging iteration or direct human editing of the code, generally more opportunities for the human to be involved would be helpful. Oftentimes it gets stuck trying to debug an issue in it's generated code and it feels as if the human is "locked out" of the process.**

**10. Currently, it usually allows for human intervention when it gets to a new step (mission prompt), or finishes a step and is asking for any final feedback. Sometimes, it might run into an error in its code, and it doesn't allow for human intervention until the code runs successfully and it's about to move onto the next step. These may be trivial errors such as syntax errors, which we humans can resolve with a single line, either as feedback or even directly onto the code product that is generated.**

**11. Generated code is not saved until the step is completed, making it more difficult of a process for the user to identify the issue and try to address it in the next iteration (adjusting prompting/feedback)**

For points 9 to 11:
First, thank you for that feedback, it's insightful and confirms a lot of the thoughts we had about the process. We will be considering this as we reimagine the user experience, aiming to facilitate more effective human interventions and immediate error correction through human interventions. Again, please try out the new version, commit: e2832eb638178f0cc86c403a8c75ed9583260d49

**12. Liked the feature of saving the runs and allowing for old projects to be reran quickly and being able to see logs and information from past runs**

Traceability and reproducibility are very important values in science. We think that implementing these features of logging, caching and replaying are important to ensure that we follow those key values - thereby AI can even enhance and not jeopardize them!

Please do not hesitate to get back to us with more observations/insights from using data-to-paper. It is exciting to see people use it!
